version: '3'
services:
  verdaccio:
    build: .
    container_name: verdaccio
    environment:
      - PORT
    ports:
      - $PORT:$PORT
    volumes:
       - verdaccio:/verdaccio
  nginx:
    build: ./nginx
    container_name: nginx
    ports: 
    - 4087:443
    restart: always
volumes:
  verdaccio:
    driver: local
